/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedMinhaExtensaoRouteImport } from './routes/_authenticated/minha-extensao'
import { Route as AuthenticatedInstalacoesRouteImport } from './routes/_authenticated/instalacoes'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated/equipe'
import { Route as ApiPublicTrackMessageRouteImport } from './routes/api/public/track-message'

const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMinhaExtensaoRoute =
  AuthenticatedMinhaExtensaoRouteImport.update({
    id: '/minha-extensao',
    path: '/minha-extensao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInstalacoesRoute =
  AuthenticatedInstalacoesRouteImport.update({
    id: '/instalacoes',
    path: '/instalacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicTrackMessageRoute = ApiPublicTrackMessageRouteImport.update({
  id: '/api/public/track-message',
  path: '/api/public/track-message',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/instalacoes': typeof AuthenticatedInstalacoesRoute
  '/minha-extensao': typeof AuthenticatedMinhaExtensaoRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/api/public/track-message': typeof ApiPublicTrackMessageRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/instalacoes': typeof AuthenticatedInstalacoesRoute
  '/minha-extensao': typeof AuthenticatedMinhaExtensaoRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/public/track-message': typeof ApiPublicTrackMessageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/_authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/_authenticated/instalacoes': typeof AuthenticatedInstalacoesRoute
  '/_authenticated/minha-extensao': typeof AuthenticatedMinhaExtensaoRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/public/track-message': typeof ApiPublicTrackMessageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/politica-de-privacidade'
    | '/equipe'
    | '/instalacoes'
    | '/minha-extensao'
    | '/perfil'
    | '/api/public/track-message'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/politica-de-privacidade'
    | '/equipe'
    | '/instalacoes'
    | '/minha-extensao'
    | '/perfil'
    | '/'
    | '/api/public/track-message'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/politica-de-privacidade'
    | '/_authenticated/equipe'
    | '/_authenticated/instalacoes'
    | '/_authenticated/minha-extensao'
    | '/_authenticated/perfil'
    | '/_authenticated/'
    | '/api/public/track-message'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  ApiPublicTrackMessageRoute: typeof ApiPublicTrackMessageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/minha-extensao': {
      id: '/_authenticated/minha-extensao'
      path: '/minha-extensao'
      fullPath: '/minha-extensao'
      preLoaderRoute: typeof AuthenticatedMinhaExtensaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/instalacoes': {
      id: '/_authenticated/instalacoes'
      path: '/instalacoes'
      fullPath: '/instalacoes'
      preLoaderRoute: typeof AuthenticatedInstalacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/track-message': {
      id: '/api/public/track-message'
      path: '/api/public/track-message'
      fullPath: '/api/public/track-message'
      preLoaderRoute: typeof ApiPublicTrackMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedInstalacoesRoute: typeof AuthenticatedInstalacoesRoute
  AuthenticatedMinhaExtensaoRoute: typeof AuthenticatedMinhaExtensaoRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedInstalacoesRoute: AuthenticatedInstalacoesRoute,
  AuthenticatedMinhaExtensaoRoute: AuthenticatedMinhaExtensaoRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  ApiPublicTrackMessageRoute: ApiPublicTrackMessageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
